bankDataModelFields = {
    "Residential First Total":"residential_first_total",
    "Residential First Charge-offs YTD":"residential_first_charge_offs_ytd",
    "Residential First Recoveries YTD":"residential_first_recoveries_ytd",
    "Residential First 30Day":"residential_first_30day",
    "Residential First 30Day Pct of Total":"residential_first_30day_of_total",
    "Residential First 30Day PG PCTL":"residential_first_30day_pg_pctl",
    "Residential First 90Day":"residential_first_90day",
    "Residential First 90Day Pct of Total":"residential_first_90day_of_total",
    "Residential First 90Day PG PCTL":"residential_first_90day_pg_pctl",
    "Residential First Nonaccrual Balance":"residential_first_nonaccrual_balance",
    "Residential First Nonaccrual Pct of Total":"residential_first_nonaccrual_of_total",
    "Residential First Nonaccrual PG PCTL":"residential_first_nonaccrual_pg_pctl",
    "Residential First Nonaccrual Qtr Chg $":"residential_first_nonaccrual_qtr_chg_field",
    "Residential First Nonaccrual Qtr Chg Pct":"residential_first_nonaccrual_qtr_chg_field_0",
    "Residential First Nonaccrual Yr Chg $":"residential_first_nonaccrual_yr_chg_field",
    "Residential First Nonaccrual Yr Chg Pct":"residential_first_nonaccrual_yr_chg_field_0",
    "Residential Jr Total":"residential_jr_total",
    "Residential Jr Charge-offs YTD":"residential_jr_charge_offs_ytd",
    "Residential Jr Recoveries YTD":"residential_jr_recoveries_ytd",
    "Residential Jr 30Day":"residential_jr_30day",
    "Residential Jr 30Day Pct of Total":"residential_jr_30day_of_total",
    "Residential Jr 30Day PG PCTL":"residential_jr_30day_pg_pctl",
    "Residential Jr 90Day":"residential_jr_90day",
    "Residential Jr 90Day Pct of Total":"residential_jr_90day_of_total",
    "Residential Jr 90Day PG PCTL":"residential_jr_90day_pg_pctl",
    "Residential Jr Nonaccrual Balance":"residential_jr_nonaccrual_balance",
    "Residential Jr Nonaccrual Pct of Total":"residential_jr_nonaccrual_of_total",
    "Residential Jr Nonaccrual PG PCTL":"residential_jr_nonaccrual_pg_pctl",
    "Residential Jr Nonaccrual Qtr Chg $":"residential_jr_nonaccrual_qtr_chg_field",
    "Residential Jr Nonaccrual Qtr Chg Pct":"residential_jr_nonaccrual_qtr_chg_field_0",
    "Residential Jr Nonaccrual Yr Chg $":"residential_jr_nonaccrual_yr_chg_field",
    "Residential Jr Nonaccrual Yr Chg Pct":"residential_jr_nonaccrual_yr_chg_field_0",
    "Residential HELOC Total":"residential_heloc_total",
    "Residential HELOC Charge-offs YTD": "residential_heloc_charge_offs_ytd",
    "Residential HELOC Recoveries YTD": "residential_heloc_recoveries_ytd",
    "Residential HELOC 30Day": "residential_heloc_30day",
    "Residential HELOC 30Day Pct of Total": "residential_heloc_30day_of_total",
    "Residential HELOC 30Day PG PCTL": "residential_heloc_30day_pg_pctl",
    "Residential HELOC 90Day": "residential_heloc_90day",
    "Residential HELOC 90Day Pct of Total": "residential_heloc_90day_of_total",
    "Residential HELOC 90Day PG PCTL": "residential_heloc_90day_pg_pctl",
    "Residential HELOC Nonaccrual Balance": "residential_heloc_nonaccrual_balance",
    "Residential HELOC Nonaccrual Pct of Total": "residential_heloc_nonaccrual_of_total",
    "Residential HELOC Nonaccrual PG PCTL": "residential_heloc_nonaccrual_pg_pctl",
    "Residential HELOC Nonaccrual Qtr Chg $": "residential_heloc_nonaccrual_qtr_chg_field",
    "Residential HELOC Nonaccrual Qtr Chg Pct": "residential_heloc_nonaccrual_qtr_chg_field_0",
    "Residential HELOC Nonaccrual Yr Chg $": "residential_heloc_nonaccrual_yr_chg_field",
    "Residential HELOC Nonaccrual Yr Chg Pct": "residential_heloc_nonaccrual_yr_chg_field_0",
    "Construction Resi Total": "construction_resi_total",
    "Construction Resi Charge-offs YTD": "construction_resi_charge_offs_ytd",
    "Construction Resi Recoveries YTD": "construction_resi_recoveries_ytd",
    "Construction Resi 30Day": "construction_resi_30day",
    "Construction Resi 30Day Pct of Total": "construction_resi_30day_of_total",
    "Construction Resi 30Day PG PCTL": "construction_resi_30day_pg_pctl",
    "Construction Resi 90Day": "construction_resi_90day",
    "Construction Resi 90Day Pct of Total":"construction_resi_90day_of_total",
    "Construction Resi 90Day PG PCTL":"construction_resi_90day_pg_pctl",
    "Construction Resi Nonaccrual Balance" : "construction_resi_nonaccrual_balance",
    "Construction Resi Nonaccrual Pct of Total": "construction_resi_nonaccrual_of_total",
    "Construction Resi Nonaccrual PG PCTL": "construction_resi_nonaccrual_pg_pctl",
    "Construction Resi Nonaccrual Qtr Chg $": "construction_resi_nonaccrual_qtr_chg_field",
    "Construction Resi Nonaccrual Qtr Chg Pct": "construction_resi_nonaccrual_qtr_chg_field_0",
    "Construction Resi Nonaccrual Yr Chg $": "construction_resi_nonaccrual_yr_chg_field",
    "Construction Resi Nonaccrual Yr Chg Pct": "construction_resi_nonaccrual_yr_chg_field_0",
    "Multi-Family Total": "multi_family_total",
    "Multi-Family Charge-offs YTD": "multi_family_charge_offs_ytd",
    "Multi-Family Recoveries YTD": "multi_family_recoveries_ytd",
    "Multi-Family 30Day": "multi_family_30day",
    "Multi-Family 30Day Pct of Total": "multi_family_30day_of_total",
    "Multi-Family 30Day PG PCTL":"multi_family_30day_pg_pctl",
    "Multi-Family 90Day":"multi_family_90day",
    "Multi-Family 90Day Pct of Total":"multi_family_90day_of_total",
    "Multi-Family 90Day PG PCTL":"multi_family_90day_pg_pctl",
    "Multi-Family Nonaccrual Balance":"multi_family_nonaccrual_balance",
    "Multi-Family Nonaccrual Pct of Total":"multi_family_nonaccrual_of_total",
    "Multi-Family Nonaccrual PG PCTL":"multi_family_nonaccrual_pg_pctl",
    "Multi-Family Nonaccrual Qtr Chg $":"multi_family_nonaccrual_qtr_chg_field",
    "Multi-Family Nonaccrual Qtr Chg Pct":"multi_family_nonaccrual_qtr_chg_field_0",
    "Multi-Family Nonaccrual Yr Chg $":"multi_family_nonaccrual_yr_chg_field",
    "Multi-Family Nonaccrual Yr Chg Pct":"multi_family_nonaccrual_yr_chg_field_0",
    "Commercial Total":"commercial_total",
    "Commercial Charge-offs YTD":"commercial_charge_offs_ytd",
    "Commercial Recoveries YTD":"commercial_recoveries_ytd",
    "Commercial 30Day":"commercial_30day",
    "Commercial 30Day Pct of Total":"commercial_30day_of_total",
    "Commercial 30Day PG PCTL":"commercial_30day_pg_pctl",
    "Commercial 90Day":"commercial_90day",
    "Commercial 90Day Pct of Total":"commercial_90day_of_total",
    "Commercial 90Day PG PCTL":"commercial_90day_pg_pctl",
    "Commercial Nonaccrual Balance":"commercial_nonaccrual_balance",
    "Commercial Nonaccrual Pct of Total":"commercial_nonaccrual_of_total",
    "Commercial Nonaccrual PG PCTL":"commercial_nonaccrual_pg_pctl",
    "Commercial Nonaccrual Qtr Chg $": "commercial_nonaccrual_qtr_chg_field",
    "Commercial Nonaccrual Qtr Chg Pct": "commercial_nonaccrual_qtr_chg_field_0",
    "Commercial Nonaccrual Yr Chg $": "commercial_nonaccrual_yr_chg_field",
    "Commercial Nonaccrual Yr Chg Pct": "commercial_nonaccrual_yr_chg_field_0",
    "Farmland Total": "farmland_total",
    "Farmland Charge-offs YTD": "farmland_charge_offs_ytd",
    "Farmland Recoveries YTD": "farmland_recoveries_ytd",
    "Farmland 30Day": "farmland_30day",
    "Farmland 30Day Pct of Total": "farmland_30day_of_total",
    "Farmland 30Day PG PCTL": "farmland_30day_pg_pctl",
    "Farmland 90Day": "farmland_90day",
    "Farmland 90Day Pct of Total": "farmland_90day_of_total",
    "Farmland 90Day PG PCTL": "farmland_90day_pg_pctl",
    "Farmland Nonaccrual Balance":"farmland_nonaccrual_balance",
    "Farmland Nonaccrual Pct of Total": "farmland_nonaccrual_of_total",
    "Farmland Nonaccrual PG PCTL": "farmland_nonaccrual_pg_pctl",
    "Farmland Nonaccrual Qtr Chg $": "farmland_nonaccrual_qtr_chg_field",
    "Farmland Nonaccrual Qtr Chg Pct": "farmland_nonaccrual_qtr_chg_field_0",
    "Farmland Nonaccrual Yr Chg $": "farmland_nonaccrual_yr_chg_field",
    "Farmland Nonaccrual Yr Chg Pct": "farmland_nonaccrual_yr_chg_field_0",
    "ALLL Total": "alll_total",
    "ALLL Total Qtr Chg $": "alll_total_qtr_chg_field",
    "ALLL Total Qtr Chg Pct": "alll_total_qtr_chg_field_0",
    "ALLL Total Yr Chg $": "alll_total_yr_chg_field",
    "ALLL Residential Loans":"alll_residential_loans",
    "ALLL Residential Loans Qtr Chg $": "alll_residential_loans_qtr_chg_field",
    "ALLL Residential Loans Qtr Chg Pct": "alll_residential_loans_qtr_chg_field_0",
    "ALLL Residential Loans Yr Chg $": "alll_residential_loans_yr_chg_field",
    "ALLL Residential Loans Yr Chg Pct": "alll_residential_loans_yr_chg_field_0",
    "ALLL Construction Loans": "alll_construction_loans",
    "ALLL Construction Loans Qtr Chg $": "alll_construction_loans_qtr_chg_field",
    "ALLL Construction Loans Qtr Chg Pct": "alll_construction_loans_qtr_chg_field_0",
    "ALLL Construction Loans Yr Chg $": "alll_construction_loans_yr_chg_field",
    "ALLL Construction Loans Yr Chg Pct": "alll_construction_loans_yr_chg_field_0",
    "ALLL Commercial Loans": "alll_commercial_loans",
    "ALLL Commercial Loans Qtr Chg $": "alll_commercial_loans_qtr_chg_field",
    "ALLL Commercial Loans Qtr Chg Pct": "alll_commercial_loans_qtr_chg_field_0",
    "ALLL Total Yr Chg Pct": "alll_total_yr_chg_field_0",
    "ALLL Commercial Loans Yr Chg $": "alll_commercial_loans_yr_chg_field",
    "ALLL Commercial Loans Yr Chg Pct": "alll_commercial_loans_yr_chg_field_0",
    "ALLL Pct of LNS&LS": "alll_of_lns_ls",
    "ALLL Pct of LNS&LS PG PCTL": "alll_of_lns_ls_pg_pctl",
    "ALLL Pct of Nonaccural LNS&LS": "alll_of_nonaccural_lns_ls",
    "ALLL Pct of Nonaccural LNS&LS PG PCTL": "alll_of_nonaccural_lns_ls_pg_pctl",
    "Provision for Loan and Lease Losses": "provision_for_loan_and_lease_losses",
    "REO Total": "reo_total",
    "REO Total Qtr Chg $": "reo_total_qtr_chg_field",
    "REO Total Qtr Chg Pct": "reo_total_qtr_chg_field_0",
    "REO Total Yr Chg $": "reo_total_yr_chg_field",
    "REO Total Yr Chg Pct": "reo_total_yr_chg_field_0",
    "REO Residential": "reo_residential",
    "REO Residential Qtr Chg $": "reo_residential_qtr_chg_field",
    "REO Residential Qtr Chg Pct": "reo_residential_qtr_chg_field_0",
    "REO Residential Yr Chg $": "reo_residential_yr_chg_field",
    "REO Residential Yr Chg Pct": "reo_residential_yr_chg_field_0",
    "REO Multi-Family": "reo_multi_family",
    "REO Multi-Family Qtr Chg $": "reo_multi_family_qtr_chg_field",
    "REO Multi-Family Qtr Chg Pct": "reo_multi_family_qtr_chg_field_0",
    "REO Multi-Family Yr Chg $": "reo_multi_family_yr_chg_field",
    "REO Multi-Family Yr Chg Pct": "reo_multi_family_yr_chg_field_0",
    "REO Construction": "reo_construction",
    "REO Construction Qtr Chg $": "reo_construction_qtr_chg_field",
    "REO Construction Qtr Chg Pct": "reo_construction_qtr_chg_field_0",
    "REO Construction Yr Chg $": "reo_construction_yr_chg_field",
    "REO Construction Yr Chg Pct": "reo_construction_yr_chg_field_0",
    "REO Farmland": "reo_farmland",
    "REO Farmland Qtr Chg $": "reo_farmland_qtr_chg_field",
    "REO Farmland Qtr Chg Pct": "reo_farmland_qtr_chg_field_0",
    "REO Farmland Yr Chg $": "reo_farmland_yr_chg_field",
    "REO Farmland Yr Chg Pct": "reo_farmland_yr_chg_field_0",
    "Residential in Foreclosure": "residential_in_foreclosure",
    "Residential in Foreclosure Qtr Chg $": "residential_in_foreclosure_qtr_chg_field",
    "Residential in Foreclosure Qtr Chg Pct": "residential_in_foreclosure_qtr_chg_field_0",
    "Residential in Foreclosure Yr Chg $": "residential_in_foreclosure_yr_chg_field",
    "Residential in Foreclosure Yr Chg Pct": "residential_in_foreclosure_yr_chg_field_0",
    "Loans Held for Sale Total": "loans_held_for_sale_total",
    "Loans Held for Sale 30Day": "loans_held_for_sale_30day",
    "Loans Held for Sale 90Day": "loans_held_for_sale_90day",
    "Loans Held for Sale Nonaccrual": "loans_held_for_sale_nonaccrual",
    "Residential Mortgages Held for Sale": "residential_mortgages_held_for_sale",
    "Residential Mortgages Sold": "residential_mortgages_sold",
    "Credit Card Total":"credit_card_total",
    "Credit Card Charge-offs YTD": "credit_card_charge_offs_ytd",
    "Credit Card Recoveries YTD": "credit_card_recoveries_ytd",
    "Credit Card 30Day": "credit_card_30day",
    "Credit Card 30Day Pct of Total": "credit_card_30day_of_total",
    "Credit Card 30Day PG PCTL": "credit_card_30day_pg_pctl",
    "Credit Card 90Day": "credit_card_90day",
    "Credit Card 90Day Pct of Total": "credit_card_90day_of_total",
    "Credit Card 90Day PG PCTL": "credit_card_90day_pg_pctl",
    "Credit Card Nonaccrual Balance": "credit_card_nonaccrual_balance",
    "Credit Card Nonaccrual Pct of Total": "credit_card_nonaccrual_of_total",
    "Credit Card Nonaccrual PG PCTL":"credit_card_nonaccrual_pg_pctl",
    "Credit Card Nonaccrual Qtr Chg $":"credit_card_nonaccrual_qtr_chg_field",
    "Credit Card Nonaccrual Qtr Chg Pct": "credit_card_nonaccrual_qtr_chg_field_0",
    "Credit Card Nonaccrual Yr Chg $": "credit_card_nonaccrual_yr_chg_field",
    "Credit Card Nonaccrual Yr Chg Pct": "credit_card_nonaccrual_yr_chg_field_0",
    "Auto Total": "auto_total",
    "Auto Charge-offs YTD": "auto_charge_offs_ytd",
    "Auto Recoveries YTD": "auto_recoveries_ytd",
    "Auto 30Day": "auto_30day",
    "Auto 30Day Pct of Total": "auto_30day_of_total",
    "Auto 30Day PG PCTL": "auto_30day_pg_pctl",
    "Auto 90Day": "auto_90day",
    "Auto 90Day Pct of Total": "auto_90day_of_total",
    "Auto 90Day PG PCTL": "auto_90day_pg_pctl",
    "Auto Nonaccrual Balance": "auto_nonaccrual_balance",
    "Auto Nonaccrual Pct of Total": "auto_nonaccrual_of_total",
    "Auto Nonaccrual PG PCTL": "auto_nonaccrual_pg_pctl",
    "Auto Nonaccrual Qtr Chg $": "auto_nonaccrual_qtr_chg_field",
    "Auto Nonaccrual Qtr Chg Pct": "auto_nonaccrual_qtr_chg_field_0",
    "Auto Nonaccrual Yr Chg $": "auto_nonaccrual_yr_chg_field",
    "Auto Nonaccrual Yr Chg Pct": "auto_nonaccrual_yr_chg_field_0",
    "Other Consumer Total": "other_consumer_total",
    "Other Consumer Revolving": "other_consumer_revolving",
    "Other Consumer Installment": "other_consumer_installment",
    "Other Consumer Charge-offs YTD": "other_consumer_charge_offs_ytd",
    "Other Consumer Recoveries YTD": "other_consumer_recoveries_ytd",
    "Other Consumer 30Day": "other_consumer_30day",
    "Other Consumer 90Day": "other_consumer_90day",
    "Other Consumer Nonaccrual Balance": "other_consumer_nonaccrual_balance",
    "Other Consumer Nonaccrual Qtr Chg $": "other_consumer_nonaccrual_qtr_chg_field",
    "Other Consumer Nonaccrual Qtr Chg Pct": "other_consumer_nonaccrual_qtr_chg_field_0",
    "Other Consumer Nonaccrual Yr Chg $": "other_consumer_nonaccrual_yr_chg_field",
    "Other Consumer Nonaccrual Yr Chg Pct": "other_consumer_nonaccrual_yr_chg_field_0",
    "Total Assets": "total_assets",
    "Net Income": "net_income",
    "Number of Employees": "number_of_employees",
}